### ISSUE TITLE
Wireless network speed reports wrong speed

### ISSUE THREAD

**Issue by demonar** [yujitach/MenuMeters#187]
On the last version, the network pane started reporting wrong speeds, my ac card is working at +700mbps and the pane reports 304mbps, to be sure about it ran a speedtest and it was confirmed.
pane reported speed:
<img width="358" alt="Screen Shot 2020-11-01 at 12 55 10" src="https://user-images.githubusercontent.com/1742284/97807896-36ef3e00-1c42-11eb-9b34-3d3d6e33ffb0.png">
system reported speed:
<img width="277" alt="Screen Shot 2020-11-01 at 12 55 30" src="https://user-images.githubusercontent.com/1742284/97807868-1e7f2380-1c42-11eb-8c7a-e149b085f2c3.png">
speedtest result:
<img width="180" alt="Screen Shot 2020-11-01 at 12 58 33" src="https://user-images.githubusercontent.com/1742284/97807889-28a12200-1c42-11eb-9181-74398d1e6bd6.png">

**Comment by yujitach** [comment]
Hi, from which utility did you take the system reported speed (in your second attached image)? 

Could you also check what the "Network Utility" says about the download speed? You can open "Network Utility" from the Network Meter.

**Comment by schwedenmut** [comment]
The second image looks like Option (⌥) + Click on the Wifi Icon, which shows further information about the current connection such as speed, ips and such.

For me, the reported speed differs between system information and menumeters, too.

**Comment by demonar** [comment]
As @schwedenmut mentioned it's the option click on the wifi pane.

**Comment by demonar** [comment]
Link speed on the network utility is showing wrong too.

**Comment by demonar** [comment]
digging a little more, on "system report", If I go to the wi-fi, the current information shows more accurate data:
<img width="134" alt="Screen Shot 2020-11-02 at 20 46 37" src="https://user-images.githubusercontent.com/1742284/97931576-ad786280-1d4c-11eb-8674-c0a9e370a704.png">

**Comment by jaegan438** [comment]
Yeah, at least in my case, it looks like the link speed currently being reported may be the maximum upload speed, rather than the download.  Just throwing that out there, in case it helps.  Not sure if that is actually the case, I haven't programmed anything in more than 20 years.

**Comment by yannpub** [comment]
I also have this 304 Mbps value, despite the '⌥ + Wifi ' option gives me 1300 Mbps.

Also since I upgraded to Big Sur, Tx/Rx values seem to 'glitch'. They are OK. Then stop and goes to zero for some seconds, and then come back. But that is most probably another issue to be created.

**Comment by yujitach** [comment]
Thanks for the report, and the "another issue" is discussed in #192.

**Comment by yujitach** [comment]
I'd like to know if the problem persists on Big Sur.

**Comment by yannpub** [comment]
Yes, it still shows 304 Mbps:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/21988643/100421273-58e4b080-3088-11eb-8e4b-46518fb364df.png">
While it still show 1300 Mbps in the '⌥ + Wifi ' 
<img width="301" alt="image" src="https://user-images.githubusercontent.com/21988643/100421490-bed13800-3088-11eb-8c4c-2c246b152cea.png">

**Comment by demonar** [comment]
same here, keeps showing the same info

**Comment by yujitach** [comment]
fixed in the commit above; will be available in the next release

**Comment by yannpub** [comment]
Looks like the issue is back in v2.1.4
I now have a speed value of 217Mbps in Menumeter, while I am still at 1300 Mbps in the '⌥ + Wifi '

**Comment by yujitach** [comment]
I didn't change a thing in the new version. Was it working in v2.1.3? If you have time, I would appreciate if you could download the old version from here https://github.com/yujitach/MenuMeters/releases/tag/2.1.3 ? Maybe it wasn't working after all...

**Comment by yannpub** [comment]
Just tried to execute v2.1.3, and you’re right, the issue is also there. But it was definitely working once you fixed it in the earlier version.

**Comment by yujitach** [comment]
Thank you very much. It would be really nice if you could go back the list of stable releases to see when it stopped working...

**Comment by yannpub** [comment]
I went multiple releases backward. It changes as expected in 2.1.2.1. But then it shows only 217, whereas it used to properly show 1300. So I guess something has changed in the latest release of BigSur (11.2).

Effectively if I get info on my connection with airport -I, I get the following result :

          state: running
        op mode: station
     lastTxRate: 1300
        maxRate: 217
lastAssocStatus: 0
    802.11 auth: open
      link auth: wpa3-sae

As you can see maxRate < lastTxRate. And maxRate is erroneously calculated here. So looks like the issue is an Apple one :-(
