### ISSUE TITLE
Memory Pressure doesn't seem to match what Activity Monitor shows

### ISSUE THREAD

**Issue by luckman212** [yujitach/MenuMeters#47]
@geigi Thank you for the contribution of the memory pressure stats.  I should have tested it earlier when it was still an open PR but since Yuji made the new binary public today I gave it a go. On my system (Mac Mini with 16GB RAM, Sierra 10.12.3) the pressure bar in MenuMeters doesn't seem to align with the values in Activity Monitor.

For example, see the screenshot below, where Activity Monitor shows pressure at around 45% but the Menubar appears to be around 25%

I then proceeded to launch as many apps as possible to try to increase the pressure, and while Activity Monitor's graph steadily increased, the MenuMeter seemed to stay stagnant.  I had my update value at 10seconds (default)

Any idea why that might be?

![image](https://cloud.githubusercontent.com/assets/1992842/22854459/0ee5a0b4-f03d-11e6-9a59-d5ece8aca95c.png)

**Comment by geigi** [comment]
Hey :)
yeah I'm aware of that issue... I'm using an unoffical API from the system which only provides 4 different values for memory pressure: normal (1), 2, warning (3) and critical (4). Activity monitor uses additional information to calculate the memory pressure that is displayed in the graph you screenshoted. There is only a little bit of information out there on how activity monitor actually calculates the memory pressure and there is no API for it available. I couldn't figure it out yet. If the graph in activity monitor gets yellow, memory pressure is in the warning state and the menu bar indicator will rise, also if it gets to the critical state (red in activity monitor). I learned everything from here: http://apple.stackexchange.com/questions/107126/what-scale-or-measure-does-mavericks-and-yosemites-memory-pressure-adhere-to

**Comment by luckman212** [comment]
I see.  Too bad there's no way to expose the "real" value displayed in Activity Monitor. In that case I believe a simple colored dot would be better: green/yellow/red. It's a bit hard to see the light green bar graph and the way it appears now, and gives you a false idea that somehow your memory pressure is only 25% when in fact it could be much higher.

**Comment by geigi** [comment]
I like your idea, it is not as misleading as the current bar. I currently don't have time to implement this but it's on my list :)

**Comment by yujitach** [comment]
https://github.com/tramdas/memstatpoller shows how to do that.

**Comment by yujitach** [comment]
resolved in the commit https://github.com/yujitach/MenuMeters/commit/9835cffe8d34edf2d862e0ce2ea970eefca78b95 . Will be available in the next release .

**Comment by CheyiLin** [comment]
With the latest `2.1.2.2`, the memory pressure still doesn't match the graph I saw in Activity Monitor:
![image](https://user-images.githubusercontent.com/2572321/102172423-b031b000-3ed3-11eb-85db-57400f17d7b7.png)

**Comment by yujitach** [comment]
You're perfectly right. I'm reopening the issue. What MenuMeters currently displays is what the command line tool `memory_pressure` reports as `System-wide memory free percentage:`.
